[start]
command:/usr/local/opnsense/scripts/OPNsense/Tang/tang.sh start
parameters:
type:script
message:Starting Tang NBDE daemon

[stop]
command:/usr/local/opnsense/scripts/OPNsense/Tang/tang.sh stop
parameters:
type:script
message:Stopping Tang NBDE daemon

[restart]
command:/usr/local/opnsense/scripts/OPNsense/Tang/tang.sh restart
parameters:
type:script
message:Restarting Tang NBDE daemon

[reload]
command:/usr/local/opnsense/scripts/OPNsense/Tang/tang.sh restart
parameters:
type:script
message:Reloading Tang NBDE daemon

[status]
command:/usr/local/opnsense/scripts/OPNsense/Tang/tang.sh status
parameters:
type:script_output
message:Requesting Tang NBDE daemon status

[keys.list]
command:/usr/local/opnsense/scripts/OPNsense/Tang/tang.sh list
parameters:
type:script_output
message:Listing Tang keys

[keys.materialize]
command:/usr/local/opnsense/scripts/OPNsense/Tang/tang.sh materialize
parameters:
type:script_output
message:Writing Tang keys to disk

[keys.keygen]
command:/usr/local/opnsense/scripts/OPNsense/Tang/tang.sh keygen
parameters:
type:script_output
message:Generating initial Tang key pair

[keys.rotate]
command:/usr/local/opnsense/scripts/OPNsense/Tang/tang.sh rotate
parameters:
type:script_output
message:Rotating Tang keys

[keys.delhidden]
command:/usr/local/opnsense/scripts/OPNsense/Tang/tang.sh delhidden
parameters:
type:script_output
message:Deleting hidden Tang keys

[log.get]
command:/usr/local/opnsense/scripts/OPNsense/Tang/tang.sh log
parameters:%s %s
type:script_output
message:Fetching Tang log

[log.clear]
command:/usr/local/opnsense/scripts/OPNsense/Tang/tang.sh clearlog
parameters:
type:script_output
message:Clearing Tang log
