PLUGIN_NAME=		tang
PLUGIN_VERSION=		i.0
PLUGIN_REVISON=		i
PLUGIN_COMMENT=		Tang is a small daemon for binding data to the presence of a network
PLUGIN_DEPENDS=		socat:net/socat \
                        tang:security/tang
PLUGIN_MAINTAINER=	hdholm@alumni.iastate.edu

.include "../../Mk/plugins.mk"
